# Created by Ansible (roles/talos create_k8s_secrets) and now managed here with SOPS (#165).
apiVersion: v1
kind: Secret
metadata:
    name: gitea-user-credentials
    namespace: gitea
type: Opaque
data:
    claude-bot-password: ENC[AES256_GCM,data:mW6hu6PIG3x0payRaouW2eidoZxB4qB6JEOf8c00BwNoqkGZIrM4xA==,iv:fa5VN7b1S3qQ1bAyC03j3vHUTRgUktrZp58EpVITrj8=,tag:aekDO93t2bI8WPj5/4IV+w==,type:str]
    umueller-password: ENC[AES256_GCM,data:neA31huYByQL0STa,iv:T6UzZ9PLzpyFGVamwqk65bJ8dtVtLrKIdY8UX4/GZtc=,tag:2gcVzQ81AQeFSu6T+lcCQg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB2OHhZaXMzYzdwTVVaVTls
            QTRISFNGbFV2YWV5UzgreGRCZDB5dzhRT1hnCmZPcFNaa0lqc1kwT3JzRzV5Q3R5
            eEdvMkt0UUlhKzM4QnFYUGkvMDF1SFkKLS0tIFQwYUdDUjRrd0JGR25NY0pqVE1Z
            MzVVQjBoY2paN1g1Rko5eWpaWklsQkEKFsbwMUVoSbKhpt7X1xUxfXeyxNAnT17j
            OoAYsam47cjAeNX5UHCVs22Jdq+/v2VMe9ZUarW0ggIZzEZpRnEx7Q==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1zq7k2f07ardejddg6fkxgh8mayu740ytu7hlw36hcr46gdtequ8q4slk2z
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-10-03T15:36:58Z"
    mac: ENC[AES256_GCM,data:g4IxEDuRNd6vclGV2HPsKV3xoNRjY2PVlgnc/4FG5FVGWiXLE1tV0qBDv/FrqXV+yEslDO7Q7CPEXL8zPPWhPH9iBN4drnQjtziz0G9HoQdmOlUOiK3u/3aN5SF7+VbN9AJ5mlHvEo3a3GtD8y38k+Jxv/Gy4lqvWbIxF5e9i+A=,iv:rqEKNdTkjvm0dCqbKDIQdHkGn2Vf3isuKg7kLWId5Oo=,tag:UPn3Jv3LSwLE+aCD4dn3Gg==,type:str]
    version: 3.13.3
