# Created by Ansible (roles/talos create_k8s_secrets) and now managed here with SOPS (#165).
apiVersion: v1
kind: Secret
metadata:
    name: gitea-postgresql-credentials
    namespace: gitea
type: Opaque
data:
    values.yaml: ENC[AES256_GCM,data:Mea8YyLXvW9sdZ4DK0Q0weHKiov6xYYzD/zPxE5R41Eu/aPYOObvzY1lBtXLbkeaZ84zHs+Qmx5QKxhlRWEjj0e7AJmu9+oxgvdckLtAhpJJkKhYnrT/pephZGtv3izWgFBuUfKYflbpoa0S,iv:kt2SdAHtuDiDxmCNdfgvIJgzH9c6iKbvlZ18PofBmtU=,tag:HqyCDEiJe+k1FdBKMC03kQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBVTHFLVVNHZklnemFHS0Jr
            MEJWWW5DM2x6SkpwY05oTHlaeGJEZ3E3ZG1JCjNaempIMHVkd1RBT29zZU1teDU4
            SnNUeWJPY3NpM05sVzM5bDhydlQ5TTQKLS0tIGRlZGIwL2xiWk5HTzQ5enp5bm55
            ZkJEZjFyajBiSXBKVGtYL2plRVRYUGsK/HUS4h/4brvMjs40f3nw7/0xiJxhqxoT
            t5npBG1B9gpwVvzxZJ+QA6pHXb6lkCPZ0TYQmasX6GkEDr/hQfdeQg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1zq7k2f07ardejddg6fkxgh8mayu740ytu7hlw36hcr46gdtequ8q4slk2z
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-10-03T15:36:58Z"
    mac: ENC[AES256_GCM,data:sGOUXcsaoBcLiB8rZS1z7ZzifWRfR2/QKF8Hp2V0Sp6kNzq5oLHySH4bMx5sINcpcuj+0OpmKn8YgqujIghpKHV9aqbV/tUMOXAxQgDXOMdaZcvZ0XNFEe22Fd2BDssoampE0FgGtIDJxNehyopC2/LbDeH/9hNXBN2ipcTtUrQ=,iv:gzIy7N6HydqscSkUXzvF7xpW9sgW41SXXMlaKyGRMdc=,tag:JCK40jIxaqBKxOMxAivpPA==,type:str]
    version: 3.13.3
