# Created by Ansible (roles/talos create_k8s_secrets) and now managed here with SOPS (#165).
apiVersion: v1
kind: Secret
metadata:
    name: gitea-admin-credentials
    namespace: gitea
type: Opaque
data:
    password: ENC[AES256_GCM,data:UxAonlrQ3/us6uYV,iv:PTkdTvXee/vy1QOD+aD1xmRa3Rdg5oA7/DmlDWCDnMM=,tag:CbCBTXt7NAvnJck5GbNSDQ==,type:str]
    username: ENC[AES256_GCM,data:7oDSVkn3DlM=,iv:kfW3fTgPfQFvF51q3zxzs6UEqdqBrk/UCLbq8h35tV8=,tag:lZXqizC+VpYRxS8lmFYI/w==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBKL1pYK3pObVJwekthamc3
            TlJoVlBzRUJ5VG1pVStiMVZHNHk1ZllXbHhvClQvRmxvR1FMaENBekNFWDhEVDYx
            YWlBUjRMVDVTMDB3NmRoQ2Q5MFQwZTQKLS0tIFFoZG14Njk3bldIaCtNMWRSSWFk
            REU5eGFjWWQ5OURtckVRZVlxNm9QVUkKhTm9kRB0xQtQcdqQTcMFL/iwgxyoS46l
            WQB027+GCaFmhxfzWP1/WgEkqAta0OmThRu5uyLc57EiTAGE97r33A==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1zq7k2f07ardejddg6fkxgh8mayu740ytu7hlw36hcr46gdtequ8q4slk2z
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-10-03T15:36:57Z"
    mac: ENC[AES256_GCM,data:FjlQxuBda/Pgg/KDlD0zxaCjTYI4QFTj1YW1t5MjpwgY09aFdh9LjWXc5pLqwcmKoFkG7XUHZnPTAheDMAVTyBkUUkWVxZREa3myyTeGR91OIt9lVvIzhq2cNVqI3fsaK8mjnrMRDQ+Mi8nJsd/AoptpmpNUjqHvQLeH2eJaJm4=,iv:DhgzN6EXQqwxFSW5rEvj3vM1hfzMJp6Qsa4WI+Sc/F4=,tag:hdyXyua/Mw03tPoEFKT61g==,type:str]
    version: 3.13.3
