apiVersion: apps/v1
kind: Deployment
metadata:
  name: gitea-runner
  namespace: gitea
spec:
  replicas: 1

  selector:
    matchLabels:
      app: gitea-runner

  template:
    metadata:
      labels:
        app: gitea-runner

    spec:
      containers:
        - name: runner
          image: docker.io/gitea/act_runner:nightly

          env:
            - name: DOCKER_HOST
              value: tcp://localhost:2376
            - name: DOCKER_CERT_PATH
              value: /certs/client
            - name: DOCKER_TLS_VERIFY
              value: "1"
            - name: GITEA_INSTANCE_URL
              value: http://gitea-http.gitea.svc.cluster.local:3000
            - name: GITEA_RUNNER_REGISTRATION_TOKEN
              valueFrom:
                secretKeyRef:
                  name: gitea-runner-credentials
                  key: registration-token
            - name: GITEA_RUNNER_NAME
              value: k8s-runner
            - name: GITEA_RUNNER_LABELS
              value: "ubuntu-latest:docker://node:16-bullseye,ubuntu-22.04:docker://node:16-bullseye,ubuntu-20.04:docker://node:16-bullseye"
            - name: GITEA_RUNNER_EPHEMERAL
              value: "0"

          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              cpu: 500m
              memory: 512Mi

          volumeMounts:
            - name: docker-certs
              mountPath: /certs

        - name: daemon
          image: docker.io/library/docker:dind

          securityContext:
            privileged: true

          env:
            - name: DOCKER_TLS_CERTDIR
              value: /certs

          resources:
            requests:
              cpu: 200m
              memory: 256Mi
            limits:
              cpu: 1000m
              memory: 1Gi

          volumeMounts:
            - name: docker-certs
              mountPath: /certs

      volumes:
        - name: docker-certs
          emptyDir: {}
