apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: headlamp
  namespace: headlamp

spec:
  interval: 30m

  chart:
    spec:
      chart: headlamp
      version: "0.43.x"
      sourceRef:
        kind: HelmRepository
        name: headlamp
        namespace: flux-system

  values:
    config:
      pluginsDir: /headlamp/plugins
      watchPlugins: true
    persistentVolumeClaim:
      enabled: true
      accessModes:
        - ReadWriteOnce
      size: 1Gi
      storageClassName: longhorn
    volumeMounts:
      - name: headlamp-plugins
        mountPath: /headlamp/plugins
    volumes:
      - name: headlamp-plugins
        persistentVolumeClaim:
          claimName: headlamp
    replicaCount: 2
    resources:
      requests:
        cpu: 100m
        memory: 128Mi
      limits:
        cpu: 500m
        memory: 256Mi
