# Values set to CHANGEME must be replaced: sops apps/production/hermes-agent/hermes-agent-secrets.sops.yaml
apiVersion: v1
kind: Secret
metadata:
    name: hermes-agent-secrets
    namespace: hermes-agent
type: Opaque
stringData:
    API_SERVER_KEY: ENC[AES256_GCM,data:g5EO/B1IA83wM7xOo+TIJUbS2jUs8m2gXq52L/KX6cLxs1JVpZyqlaZAb0/7U6ASroU8ZTgP6WmpNIUjFq2k6g==,iv:/lbub90duA5IsjLf1fIlGOMb47yKBkLYpMfl7WiG5Wc=,tag:NSs3G6dUZc6w4qn5Mtatqg==,type:str]
    HERMES_DASHBOARD_BASIC_AUTH_USERNAME: ENC[AES256_GCM,data:MlagftM=,iv:rgWJ/59l34l5Ar+OykDfLHMoqF6c12DZv7zQBVXSKP4=,tag:J5Veq3DFbabYFOLIWFkovQ==,type:str]
    HERMES_DASHBOARD_BASIC_AUTH_PASSWORD: ENC[AES256_GCM,data:ude/Y6obJKMPUzjZGrTGqexEkjPIFqtrrBj01euB3U0=,iv:SdzwXWVenZbeM33RMzk+cUdV7k1bBELm6awIpzm6EoU=,tag:UZZWSKb/7GalQtXv+YvBPA==,type:str]
    FREELLMAPI_API_KEY: ENC[AES256_GCM,data:lD5unTCRnoM=,iv:VdVapmqJjuZunmICS4eqWsJJe/V7xnFN4h/zSOhsndg=,tag:zvBteIHlMoUG5HlylnJ5kQ==,type:str]
    TELEGRAM_BOT_TOKEN: ENC[AES256_GCM,data:gLSJiLtMEwM=,iv:U9K67ZjvhBvJP0ptDQAUUh7RnP6lWK4/Hq5ujLRYn0o=,tag:wHewmh2nJTiYYzw2YVikTw==,type:str]
    TELEGRAM_ALLOWED_USERS: ENC[AES256_GCM,data:PF4TfcFESH8=,iv:mjicDMplYEj01TelKWiHPWxOZeHms/BlAZkvohNdh6E=,tag:I1rC6J/YJlFrV/dOeRLbAg==,type:str]
    DISCORD_BOT_TOKEN: ENC[AES256_GCM,data:pG2DRSOw7Nk=,iv:iTSbq0lkrrqSyVzJN5kx3rf4sPr+4nU1CDBjIC+bsho=,tag:sQn62prdPqeslfplRpXM0Q==,type:str]
    DISCORD_ALLOWED_USERS: ENC[AES256_GCM,data:CrQxwgkz1II=,iv:W/vGo+Hs8ZojlQdr6txW4aYEJgfcKA4sStN+o9l49Ek=,tag:tIfQA4a4rR0/JqdjkRMCIw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBGdlpWUDZpM2ZpYmo2MHdX
            aU1YWHpKNGYrQ0JNa3lCTUF2VnZGOUJNbEUwCkR2WEVuWU53RGl4T0VPeXFFOUkw
            bEFZcTZ1VTFqb0hBbTNBY09SNmZEYU0KLS0tIE9hYVZrUVVCUVdwN1UxMTVDMjVJ
            RE1xM2xpSVdZQ1FiMFEyMjlBZ1RnVzAKKPwNflKfFLmP8PtBVfZpfJBSA2ZC3oB2
            z7fJLb9tV/6klm8VcO4wudasGp8RP+X/D3sBaS+4pXAwINRY7yXbjg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1zq7k2f07ardejddg6fkxgh8mayu740ytu7hlw36hcr46gdtequ8q4slk2z
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-10-08T20:58:49Z"
    mac: ENC[AES256_GCM,data:xb9EgF3KtpFjtyipFuGxkzckTNTVslFwu2td43hIzfX/XhkdAtn5HzvHfBbTr0ig+TlAdohrf6ZvwIy4DmRe3dgosiPtQXPELqQ4qqO5tH3rudpZ6pq6H2jVasODbdErnQ7NunKWIW/1JtAiKjfbPAPeKhMDXCzhDbJ6ocMPoJ8=,iv:qbyvvbTOSAQ96+1E7Lxxk1orucDZIfrM88zjRZGHIWQ=,tag:gzvtorDpXBZE6p4T0xAQmg==,type:str]
    version: 3.13.3
