# Values set to CHANGEME must be replaced: sops apps/production/hermes-agent/hermes-agent-secrets.sops.yaml
apiVersion: v1
kind: Secret
metadata:
    name: hermes-agent-secrets
    namespace: hermes-agent
type: Opaque
stringData:
    API_SERVER_KEY: ENC[AES256_GCM,data:g5EO/B1IA83wM7xOo+TIJUbS2jUs8m2gXq52L/KX6cLxs1JVpZyqlaZAb0/7U6ASroU8ZTgP6WmpNIUjFq2k6g==,iv:/lbub90duA5IsjLf1fIlGOMb47yKBkLYpMfl7WiG5Wc=,tag:NSs3G6dUZc6w4qn5Mtatqg==,type:str]
    HERMES_DASHBOARD_BASIC_AUTH_USERNAME: ENC[AES256_GCM,data:MlagftM=,iv:rgWJ/59l34l5Ar+OykDfLHMoqF6c12DZv7zQBVXSKP4=,tag:J5Veq3DFbabYFOLIWFkovQ==,type:str]
    HERMES_DASHBOARD_BASIC_AUTH_PASSWORD: ENC[AES256_GCM,data:ude/Y6obJKMPUzjZGrTGqexEkjPIFqtrrBj01euB3U0=,iv:SdzwXWVenZbeM33RMzk+cUdV7k1bBELm6awIpzm6EoU=,tag:UZZWSKb/7GalQtXv+YvBPA==,type:str]
    FREELLMAPI_API_KEY: ENC[AES256_GCM,data:c870ve0qu7s1Xb4uOJXc5QH21ii1yrZWpdJljvJYIV0i/rrQ95mAxIkB44dsCnRaGMbpMdjY58Bbb70ZA1q5UQ==,iv:RozqbZYMbryHuKabU5ieIbK3N0g1VPyBysU5Ff4yRY8=,tag:zl9tyvIydDQlJ5O1TJGg6g==,type:str]
    TELEGRAM_BOT_TOKEN: ENC[AES256_GCM,data:O3bNUdW+Kigw1mtDGnwqm7B+KO2A9zEDW2u4l9zoxPYjKmuPA4CCV5+GZsRCvQ==,iv:3iLyKC7NsriUNU2VoLdn4fX2Z08CKrAb6JULlrb3gvg=,tag:wqXxtNj+1keTz7UCNObp8Q==,type:str]
    TELEGRAM_ALLOWED_USERS: ENC[AES256_GCM,data:qP6/EkOIC5MdTA==,iv:CqE2UuJ3SqwHYjAqubSZocj0iubwDDJXjSuoES92wTw=,tag:oW6A3HnfsxtwpSp9MoPukw==,type:str]
    DISCORD_BOT_TOKEN: ENC[AES256_GCM,data:nVAnnSXWAuphUsjb7wxiSQlFGX9LTV/pjz1gGgtGUwEsN3MvuQrxAHl3ElG5uKjBWPY6Mfm7wwLbIaFPdZsYxT2uJ9Lkr0YO,iv:G0c5BgN61IgTiV00+9YwFF/bNMZvZP2VGZq5N9GwVZI=,tag:xqCiGNW/3xM3PXzk/p3uWQ==,type:str]
    DISCORD_ALLOWED_USERS: ENC[AES256_GCM,data:yMi6uSReuopZ3NyfZrjSGXtq,iv:VsqWsZK5btLFwALokHYJpEzgHSLaoxCMZjodekfHFI8=,tag:aagrvSJlGEileOQc08NOFQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBGdlpWUDZpM2ZpYmo2MHdX
            aU1YWHpKNGYrQ0JNa3lCTUF2VnZGOUJNbEUwCkR2WEVuWU53RGl4T0VPeXFFOUkw
            bEFZcTZ1VTFqb0hBbTNBY09SNmZEYU0KLS0tIE9hYVZrUVVCUVdwN1UxMTVDMjVJ
            RE1xM2xpSVdZQ1FiMFEyMjlBZ1RnVzAKKPwNflKfFLmP8PtBVfZpfJBSA2ZC3oB2
            z7fJLb9tV/6klm8VcO4wudasGp8RP+X/D3sBaS+4pXAwINRY7yXbjg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1zq7k2f07ardejddg6fkxgh8mayu740ytu7hlw36hcr46gdtequ8q4slk2z
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-10-08T21:19:24Z"
    mac: ENC[AES256_GCM,data:+bWZ6Xt9HkcjGU5NRwUtU/Ct3XTecdIgkYSLnjZxMg0l9vyH3BbLl81xIAi3ZNAg21en8WYSGTzTlTly/2XgWPekZy7j0fGMPip3rSk/Crto6NzIKHHsrn8QH+owexaiyEU9rd7yWE+1kgBW02+npreoLPoYzVWbhZmGWq3IIV4=,iv:8UjJNf97SXLxt7LTRZ4EfS9xwWRgI8UvVwGyegi77UI=,tag:SlH572YYMKPuod0oZKlOPw==,type:str]
    version: 3.13.3
