apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: metrics-server
  namespace: flux-system
spec:
  interval: 1h
  url: https://github.com/kubernetes-sigs/metrics-server
  ref:
    tag: v0.8.1
