# clusters/production/storage/longhorn/namespace.yaml
apiVersion: v1
kind: Namespace
metadata:
  name: metrics-system
#  labels:
#    # Longhorn uses this label for component identification
#    app.kubernetes.io/name: longhorn
#    app.kubernetes.io/part-of: longhorn
#
#    # Longhorn requires privileged workloads (hostPath, privileged containers)
#    pod-security.kubernetes.io/enforce: privileged
#    pod-security.kubernetes.io/audit: privileged
#    pod-security.kubernetes.io/warn: privileged
