apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base/paperless
  - paperless-secrets.sops.yaml
  - paperless-passwords.sops.yaml
  - paperless-ingest.sops.yaml
  - paperless-backup-nas.sops.yaml
