apiVersion: v1
data:
    PAPERLESS_DBPASS: ENC[AES256_GCM,data:HW1Q3JE28muqIXftVMOUj1d46gO42KWsMJQYof5wnvz4BQkPZpk4p71uSEghShLmY5oDjHYzvhl0tyzWU3qtQQ==,iv:5cvANt6UBCQTDOGlKDxqQHPEcaU17e2Xjsjom8g6v1M=,tag:k6AUrbPqUBMjFep6iPUIEA==,type:str]
    PAPERLESS_SECRET_KEY: ENC[AES256_GCM,data:4b3ja+x369Lcm0yA288ccX+8eQqL6kyjiUYWXPUzmey939DzmUsdSjrZOBsWNU4DEesUWpgULHVUZiKdveMOzF+v5ky+pJincFq5E+I8hGYqI6nQs7tvKA==,iv:poEztrR6+t4rgyUY/fpG5b/AxP88fZn55Tu39rlPD5k=,tag:XkeE42w5VYsXkEgy4375GA==,type:str]
    POSTGRES_PASSWORD: ENC[AES256_GCM,data:I5471nBsRFBeVoWglxAhEtKan/EpcnHcMIRbwlY39CqPavzFV6GS6Hz1sn/KXbZiFyiQJvhbw2EcqOJ1dsNouA==,iv:RYExcPKMODjnJTMUg8g8JGNxjyUZmPCnp1hEU+vSr1c=,tag:o6A0KIp1jiY92FU3jeDA9w==,type:str]
kind: Secret
metadata:
    name: paperless-secrets
    namespace: paperless
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBPaUFVWXNic2tvVVRxV21O
            ZmpCSjNkRXhDbXpoMkEwZXlleTFJREpGWjEwCkRXMDY4dEV5OStTWGNGOEJwUHRj
            c2dtcm14L2IyMVVNNXNZa1o5UzBXM3MKLS0tIGhhcTh1T2lsUHlnT09ybHR5aGo0
            VG1WSEtIZzNtOXRBQUxKR2lCSnFjRVkKvUaNV+DCmtWK8Sh0JtSgzLniE01QdK5F
            pvMKWLqnneF+omp6PLp/Y53/Q54U0YshH4OGbY3vt3FNn+S8C/8DIA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1zq7k2f07ardejddg6fkxgh8mayu740ytu7hlw36hcr46gdtequ8q4slk2z
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-10-09T20:48:38Z"
    mac: ENC[AES256_GCM,data:Mvi8jp7/ehX03g4PUJ0s862XUAvbUtEbcFYS19ocqJNQmwiAfLbi7mBKpCniuFtaXpLBunYk70Xikc7WoP23a1vwy4GOrT31kHbLyZApsw2ZdSSWrmtrQk5zXMK4xXmxHDxuBgvLwTISx6ZwftvzTWa8V0CJlb+Bu5NurVIfKEk=,iv:D3C6vm/g6bHxq/i03C0wdzE9otLR49xxAinZ0yIs7do=,tag:4shCZeUGjNaAlumTWOnyiQ==,type:str]
    version: 3.13.3
