apiVersion: v1
data:
    passwords.txt: ENC[AES256_GCM,data:9i4kX2ZhIsLc6+WhnrWg/Q==,iv:Uihwdb8BZ8C3k4B2Os6Caxxx7RIJw76pqZ5K8zeFgO0=,tag:5s29hUiPwMwjgvZ10igSCA==,type:str]
kind: Secret
metadata:
    name: paperless-passwords
    namespace: paperless
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBkRHlSS2tuR3ozVmdxa2FB
            aVlTSG43bU5MTWw0dDhTSDBvd1BzZVpWdHpzCjY5alFDNS9ZQlBEdGw1Z3BXZ2du
            QnNVR2FkMEtlUkhVSFk1RUtoUk5HclEKLS0tIHQ1bERPVkNxY2NldkVrRlhjL2Ja
            ZkhjT1VHQ1krdDFacndhZWIvbjM3U3cK+LgAX5SNcjocJ2xeWg+2nYDyKVoE9WfP
            ToTWQc2Kn0xSExvEQMebaRtJ7p4jMniEj1DejlKdGRvBdiIRa30u3w==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1zq7k2f07ardejddg6fkxgh8mayu740ytu7hlw36hcr46gdtequ8q4slk2z
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-10-09T20:48:40Z"
    mac: ENC[AES256_GCM,data:VXdLDUgRrQOiSHW0C9WVb/+WwfOX/ykYiOsEZtkFM098vEJn6etf/OHlv1VOMrSdvQ2Wvg67cKqRLN80aIXDRdWq7SW4ySgzqLipbh0pe4X0Nd4Sslrb36gp6YtAztzj8KBeggDAFX8rtraF8fDv2Fgqs2ItLfwnvvMRw6Eq+7E=,iv:cqP5ISBoIx2jz725EZzq8wTwUe35R/lsU6ZgCT7T07Q=,tag:/QKDwmfSfm2W08wUKDNRVg==,type:str]
    version: 3.13.3
