apiVersion: v1
kind: Secret
metadata:
    name: influxdb-admin
    namespace: influxdb
type: Opaque
stringData:
    username: ENC[AES256_GCM,data:XfZZkJU=,iv:vViuJwRL1s9bEb67urU8dUbGQQ9CgXKtum83eRzI2jM=,tag:F4K4YPLHzFW3v7LfDv5vgQ==,type:str]
    password: ENC[AES256_GCM,data:95tQ/mcBAYw8,iv:YuYTl/919LVs+V/eIdZSet2Hm6mrD0v1xPTKMUFtOm0=,tag:6LAE4vmLAz8rwLu5k3IbFw==,type:str]
    token: ENC[AES256_GCM,data:81b9fpZKyMb+JX0zZ33ZneCxVkM=,iv:RvZKR5nwX5ncH0ySuNNXtesbyYQ7zIZMrf+9eOuMNPA=,tag:QIdAun1H4vg8+v4VDUtx0A==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBpalYvMWp3K1MwUDBsTXRo
            QWRXSXpYZWtFNnVwQi9kdXdhNm0yRFE3a1dVCmNGVWZGY1EwZzVMakZXM215TVI4
            dzI5NWFRQW91OWlTY1FBQ3ByN3JvVk0KLS0tIEJGVHI2dlB2c3JRbkxMeW8zM1hn
            Qy9WdTIvUVUrYVlmU1FXcWNsN2ZMVWsKm1NYSUXZJCXOfksUoFSIvZq8hdz62OXz
            ACeW4nZBlFdk+sqLTxEKsGrvv18KTCELlLWOGTDPpUwjPYfyq7NVYw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1zq7k2f07ardejddg6fkxgh8mayu740ytu7hlw36hcr46gdtequ8q4slk2z
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-10-05T20:04:40Z"
    mac: ENC[AES256_GCM,data:/jR2YxqOSMwxb9jqMluRnyuCttwcvC02v3shmgJkOj7NrIdB3uFmkAZtHObJv+v3pda3SOVTHFZFXEQ4eP8yc9wY+VASFSa7yR2NlefZsl2ngoH88AU6T65BCFTqmlRzelbVRb8t/+8lRF6NvksUJxygR6poA35RxN5Xzdt8IMQ=,iv:hAioiowoNPjUJJw0hdJeQOnySg3LJ9Q2CprdGOGqGh0=,tag:sTsbwtsx/QUf3+RL9G9u+A==,type:str]
    version: 3.13.3
