apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: mosquitto
  namespace: mosquitto
  labels:
    release: prometheus
spec:
  selector:
    matchLabels:
      app: mosquitto
  endpoints:
    - port: metrics
      interval: 30s
