apiVersion: v1
kind: Secret
metadata:
    name: homepage-credentials
    namespace: homepage
type: Opaque
stringData:
    HOMEPAGE_VAR_UNIFI_PASSWORD: ENC[AES256_GCM,data:8D7cq7a/1eIpSY/DQlIh5Q==,iv:Ag8bX7w1ZwCkFms2Sy5MRZV2yOe3843dyMDya/ZChLE=,tag:o5cP5+//KivqsBWlusGS9Q==,type:str]
    HOMEPAGE_VAR_PAPERLESS_PASSWORD: ENC[AES256_GCM,data:Q/drEJ+oknfb,iv:uBdZ4fy654EJz5JlZeG3fM+w1VmIE32bZ81DRcp+vyU=,tag:TAIxekAi7fbEOFu0Fj65rg==,type:str]
    HOMEPAGE_VAR_PIHOLE_KEY: ENC[AES256_GCM,data:Ab49WmdkYXHlFQSmY2Tn3YfA0ki3+rG/KdPmUx9Unh2HtyVgn27eRzzK4oI=,iv:Q2fINdOu5HzuI9Y4vhpGBcka/vPv8SyOcioE8CccQO8=,tag:BCQnOgq3HBOQc8StrjkeRg==,type:str]
    HOMEPAGE_VAR_PROXMOX_TOKEN_SECRET: ENC[AES256_GCM,data:Iczf9TWf+4ehj2IvV8vstlzkef5tMAR+SfVrqm7FreZD93wJ,iv:rMMuSjsuT/IWLVPN6izSgKXP2lRw6pvzLWDIkcLtp24=,tag:Btmm2ZUCwxriZHsG8745lg==,type:str]
    HOMEPAGE_VAR_BESZEL_PASSWORD: ENC[AES256_GCM,data:Afmnqso0LyqP,iv:sIcsvsC6kIEYAZDDR9sKXA2ELMu16Q18fA3ivbVYq2o=,tag:wXhyIijd+PMQvHUF0U05fg==,type:str]
    HOMEPAGE_VAR_NPM_INTERN_PASSWORD: ENC[AES256_GCM,data:IqHC8P0kJ+t3,iv:mQ7m7Wiy6EGL7tpjA/hp7Ywzuh5PTyI6id1Hjhti8Yk=,tag:06qavGsNdXC2G1IQc6sqMw==,type:str]
    HOMEPAGE_VAR_NPM_EXTERN_PASSWORD: ENC[AES256_GCM,data:E4cRdEVzPW8A,iv:FjIUEu2JETbFMGnKgbonlxO724+c4LuNcMr6wi6tIxE=,tag:3cne0turL3VSv7WK4anIOw==,type:str]
    HOMEPAGE_VAR_QNAP_PASSWORD: ENC[AES256_GCM,data:UxeHTGLQ9ijc,iv:eE+NpDJpSWOfRJChpemzOa45oHJoGlNA4zMkLG1dDvg=,tag:BOezMyfhb2XAzj8bRXuPdw==,type:str]
    HOMEPAGE_VAR_OCTOPRINT_KEY: ENC[AES256_GCM,data:ArihxsAfjzYVjLDIUbNz23OVAtpKr2n0V51LJisOYKWK3cRBErUxorUlYg==,iv:0TK0Y48kxUzRUlydut3w4h14gQ8PfxG5t459jQH3M9c=,tag:S1kRLgvFinyi0WATbS6uYg==,type:str]
    HOMEPAGE_VAR_ESPHOME_PASSWORD: ENC[AES256_GCM,data:/Mkoawat9gLX,iv:iCtBZ5hme6JltToGklbnBilesucj72HDxP3fipu2fr8=,tag:UNuzZlTOZtLcO0fgobGHsg==,type:str]
    HOMEPAGE_VAR_GRAFANA_PASSWORD: ENC[AES256_GCM,data:ALe1lIE/z/aH,iv:6TwnMQLrKIKy43m9IYLIBZBWy2bVkTeSDiOCV7K0fPA=,tag:OobIqZK3wntt7l1jThH5IA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBhV2Mybm1UR09VWkF2VXE1
            dnc5VlBVNGg3UitlNzcrS0FXRjBmTk5wTnhrClJHVHJiTmVxek1CUzc4aklJR2dy
            ZUxWOG1VMC92TXNFN3FOK1FQVHVXZ1EKLS0tIEUwd0tPZllma0R4OTFURkpWTUY3
            OW90bStHS0t5cWc3Q2FEQlZkNnRUa1EK+a6r06YpFxqiupMKK9RJfZLyBnQzpkQj
            JHpHilGb5Zr9YTmZsfDLQPTSUfzpcrZTo/YCMvBDZthy0btdW2OCsg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1zq7k2f07ardejddg6fkxgh8mayu740ytu7hlw36hcr46gdtequ8q4slk2z
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-26T01:06:49Z"
    mac: ENC[AES256_GCM,data:t5LMUjQWQxEIoaAn9+RYnUkh1eOotTvrxq0EyLJ3pzVWm35pIPH+EiZAUkOk3utZNLiOHrGn1UzKmgMJ4YMfAWay7Q2o5TdrCKu5RkI+txM2geP8dA6s40F8Locg0B1nX/NDjwYbelAgCj1uoMyxHw+7LNZhFmCxROweOd/5H9Q=,iv:BBcRdSfIjKIpdFQxmgSYnWLNTuAATjgtNWMMfvM3ehI=,tag:iZj0/8m5xfIwu7z0jK3brA==,type:str]
    version: 3.13.3
