apiVersion: cert-manager.io/v1
kind: Certificate

metadata:
  name: wildcard-homelab
  namespace: traefik

spec:
  secretName: wildcard-homelab-tls

  issuerRef:
    kind: ClusterIssuer
    name: letsencrypt-staging

  commonName: '*.homelab.cs-ol.de'

  dnsNames:
    - homelab.cs-ol.de
    - '*.homelab.cs-ol.de'
