apiVersion: v1
kind: PersistentVolume
metadata:
  name: tasmoadmin-data
spec:
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: ""
  nfs:
    server: 192.168.1.240
    path: /share/MD0_DATA/homelab/volumes/tasmoadmin
