apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: tasmoadmin-data
  namespace: tasmoadmin
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: ""
  volumeName: tasmoadmin-data
  resources:
    requests:
      storage: 2Gi
