apiVersion: v1
kind: ConfigMap
metadata:
  name: homepage
  namespace: homepage
  labels:
    app.kubernetes.io/name: homepage
data:
  kubernetes.yaml: |
    mode: cluster
    traefik: true
  settings.yaml: ''
  #settings.yaml: |
  #  providers:
  #    longhorn:
  #      url: https://longhorn.my.network
  custom.css: ''
  custom.js: ''
  bookmarks.yaml: |
    - Developer:
        - Github:
            - abbr: GH
              href: https://github.com/
  services.yaml: |
    - My First Group:
        - My First Service:
            href: http://localhost/
            description: Homepage is awesome

    - My Second Group:
        - My Second Service:
            href: http://localhost/
            description: Homepage is the best

    - My Third Group:
        - My Third Service:
            href: http://localhost/
            description: Homepage is 😎
  widgets.yaml: |
    - kubernetes:
        cluster:
          show: true
          cpu: true
          memory: true
          showLabel: true
          label: "homelab"
        nodes:
          show: true
          cpu: true
          memory: true
          showLabel: true
    - longhorn:
        # Show the expanded
        expanded: true
        # Shows a node representing the aggregate values
        total: true
        # Shows the node names as labels
        labels: true
        # Show the nodes
        nodes: true
        # An explicit list of nodes to show. All are shown by default if "nodes" is true
        include:
          - 
          - node2
    - resources:
        backend: resources
        expanded: true
        cpu: true
        memory: true
        network: default
    - search:
        provider: duckduckgo
        target: _blank
  docker.yaml: ''
  proxmox.yaml: |
    pve:
      url: https://192.168.1.27:8006
      token: root@pam!homepage
      secret: c1337400-bccc-43fe-abd9-3e73e862cc4b


