apiVersion: v1
kind: ConfigMap
metadata:
  name: homepage
  namespace: homepage
  labels:
    app.kubernetes.io/name: homepage
data:
  kubernetes.yaml: |
    mode: cluster
    traefik: true
  settings.yaml: |
    title: Muellernetz.de Homepage
    startUrl: http://homepage.homelab.cs-ol.de
    theme: dark

    useEqualHeights: true
    showStats: true
    providers:
      longhorn:
        url: https://longhorn.homelab.cs-ol.de/

  custom.css: ''
  custom.js: ''
  bookmarks.yaml: |
    - Developer:
        - Github:
            - abbr: GH
              href: https://github.com/umueller74
        - Dashboard icons:
            - abbr: DI
              href: https://github.com/homarr-labs/dashboard-icons/tree/main/png
    - Websites:
        - IONOS:
            - abbr: IO
              href: https://mein.ionos.de/home/products?origin=CC.NGH.DE&continue
        - Serverprofis:
            - abbr: SP
              href: https://service.serverprofis.net/clientarea.php
        - cPanel:
            - abbr: CP
              href: https://cp141.sp-server.net:2083/

        - Mega.io:
            - abbr: ME
              href: https://mega.io/login

    - Entertainment:
        - YouTube:
            - abbr: YT
              href: https://youtube.com/
        - Finanzfluss:
            - abbr: FF
              href: https://www.youtube.com/@Finanzfluss

    - Kapital:
        - Raisin:
            - abbr: RA
              href: https://raisin.com/de-de/dashboard
        - Scalable Capital:
            - abbr: SC
              href: https://secure.scalable.capital/u/login
        - Comdirect:
            - abbr: CO
              href: https://kunde.comdirect.de/lp/wt/login
        - DKB:
            - abbr: DB
              href: https://banking.dkb.de/login
  services.yaml: |
      #- Primary Services:
      - Unifi Controller @ UDM Pro:
          href: https://192.168.0.1/
          description: Control your home
          icon: unifi.png
          siteMonitor: https://192.168.0.1
          widget:
              type: unifi
              url: https://192.168.0.1
              username: homepage
              password: 4om3p@gePassw0rd

      - Home Assistant:
          href: http://192.168.1.28:8123/
          description: Automate your home
          icon: home-assistant.png
          server: docker-lab1
          container: homeassistant
          widget:
              type: homeassistant
              url: http://192.168.1.28:8123
              key: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJjMjc1MjA1ZWJiMTE0ZWQzYWRmZmI2NmJjOTEyMjJiNyIsImlhdCI6MTc2NDUwODkxNCwiZXhwIjoyMDc5ODY4OTE0fQ.dMsrNydPd0ZSEpD3U-nJyHcCZp_bP0PAGc8ynIVnvzY

      - Paperless:
          href: http://192.168.1.28:8001/
          icon: paperless.png
          server: docker-lab1
          container: paperless-webserver-1
          widget:
              type: paperlessngx
              url: http://192.168.1.28:8001/
              username: mueller
              password: 'Mu5Pbm3M!'

      - PiHole:
          href: http://192.168.1.29:3180/admin
          server: docker-lab2
          container: pihole
          icon: si-pihole-#96060C
          widget:
              type: pihole
              url: http://192.168.1.29:3180
              version: 6
              key: m73ytQBhQcHMRwNE28DiAPCcSevPeRbOOwdB0WDPo9k=

      - Proxmox Macmini:
          href: https://192.168.1.27:8006/
          icon: proxmox.png
          widget:
              type: proxmox
              url: https://192.168.1.27:8006
              username: root@pam!homepage
              password: c1337400-bccc-43fe-abd9-3e73e862cc4b
              cluster: homelab

      - Proxmox Acemagic:
          href: https://192.168.1.24:8006/
          icon: proxmox.png

      - Gitea:
          href: http://192.168.0.239/
          icon: gitea.png
          widget:
              type: gitea
              url: http://192.168.0.239
              key: giteaapitoken

      - Ansible Semaphore:
          href: http://192.168.1.28:1200/
          icon: semaphore.png
          server: docker-lab1
          container: semaphore-semaphore-1

      - Beszel Monitoring:
          href: http://192.168.1.29:8099/
          icon: beszel.png
          server: docker-lab2
          container: beszel
          widget:
              type: beszel
              url: http://192.168.1.29:8099
              username: info@cs-ol.de
              password: Mu5Pbm3M!
              version: 2 # optional, default is 1

      - 'Uptime Kuma':
          href: http://10.7.0.9:3001/
          icon: uptime-kuma.png
          server: docker-ionosxs
          container: uptime-kuma
          widget:
              type: uptimekuma
              url: http://10.7.0.9:3001
              slug: overview

      #- Code:
      - NGINX Proxy Manager - INTERN:
          href: http://192.168.0.54:8081/
          icon: nginx-proxy-manager.png
          server: docker-raspi2
          container: nginx-app-1
          widget:
              type: npm
              url: http://192.168.0.54:8081
              username: info@cs-ol.de
              password: Mu5Pbm3M!

      - NGINX Proxy Manager - EXTERN:
          href: http://10.7.0.9:8081/
          icon: nginx-proxy-manager.png
          server: docker-ionosxs
          container: nginx-app-1
          widget:
              type: npm
              url: http://10.7.0.9:8081
              username: info@cs-ol.de
              password: Mu5Pbm3M!

      - QNAP:
          href: http://192.168.1.240/
          siteMonitor: http://192.168.1.240/
          icon: qnap.png
          widget:
              type: qnap
              url: http://192.168.1.240:8080
              username: mueller
              password: 'Mu5Pbm3M!'

      #- Prometheus Stack:
      - Prometheus:
          href: http://192.168.1.28:9090/
          icon: prometheus.png
          server: docker-lab1
          container: prometheus
          widget:
              type: prometheus
              url: http://192.168.1.28:9090

      - Prometheus LOKI:
          href: http://192.168.1.28:4100/
          siteMonitor: http://192.168.1.28:4100/metrics
          icon: loki.png
          server: docker-lab1
          container: loki

      - InfluxDB 2:
          href: http://192.168.1.28:8086/
          siteMonitor: http://192.168.1.28:8086/
          icon: influxdb.png
          server: docker-lab1
          container: influxdb

      # - Tools:
      - Octoprint:
          href: http://192.168.1.177/
          siteMonitor: http://192.168.1.177/
          icon: octoprint.png
          widget:
              type: octoprint
              url: http://192.168.1.177
              key: FdjL_Bj8BtjDzGvcl5vrl__zaaWn_hWrvFW85aGABmY

      - ESPHome:
          href: http://192.168.1.28:6052/
          icon: esphome.png
          server: docker-lab1
          container: esphome
          widget:
              type: esphome
              url: http://192.168.1.28:6052
              username: admin
              password: Mu5Pbm3M!

      - TasmoAdmin:
          href: http://192.168.1.28:8000/
          icon: tasmoadmin.png
          server: docker-lab1
          container: tasmoadmin

      - WishList:
          href: http://192.168.1.28:3280/
          icon: wishlist.png
          server: docker-lab1
          container: wishlist-app

      #- Monitoring:
      - Observium:
          href: http://192.168.1.28:8888/
          description: Monitor the network devices
          icon: observium.png
          server: docker-lab1
          container: observium-app-1

      - Grafana:
          href: http://192.168.1.28:3001/
          icon: grafana.png
          server: docker-lab1
          container: grafana
          widget:
              type: grafana
              version: 2
              alerts: grafana
              url: http://192.168.1.28:3001
              username: admin
              password: Mu5Pbm3M!

      - NTFY:
          href: https://ntfy.meatweb2.duckdns.org/
          siteMonitor: https://ntfy.meatweb2.duckdns.org/
          icon: ntfy.png
          server: docker-ionosxs
          container: ntfy

      #- Devices:
      - Stromzähler:
          href: http://192.168.1.74
      - Gaszähler:
          href: http://192.168.1.75
      - Wasserzähler:
          href: http://192.168.1.73
      - Gartenwasser P47:
          href: http://192.168.1.76
      - Gartenwasser P47A:
          href: http://192.168.1.77
      - Drucker Brother MFC-L2960DW:
          href: http://192.168.0.220
          description: printer Web Admin
          icon: printer.png
          siteMonitor: http://192.168.0.220

      - Drucker Kyocera:
          href: http://192.168.1.107
          description: printer Web Admin
          icon: printer.png
          siteMonitor: http://192.168.1.117

  widgets.yaml: |
    - kubernetes:
        cluster:
          show: true
          cpu: true
          memory: true
          showLabel: true
          label: "cluster"
        nodes:
          show: true
          cpu: true
          memory: true
          showLabel: true
    - longhorn:
        # Show the expanded
        expanded: true
        # Shows a node representing the aggregate values
        total: true
        # Shows the node names as labels
        labels: true
        # Show the nodes
        nodes: true
    - resources:
        backend: resources
        expanded: true
        cpu: true
        memory: true
        network: default
    - search:
        provider: duckduckgo
        target: _blank
  docker.yaml: |
    docker-lab1:
      host: 192.168.1.28
      port: 2375

    docker-lab2:
      host: 192.168.1.29
      port: 2375

    docker-lab3:
      host: 192.168.0.239
      port: 2375

    docker-raspi1:
      host: 192.168.0.50
      port: 2375

    docker-raspi2:
      host: 192.168.0.54
      port: 2375

    docker-mamapi:
      host: 192.168.100.98
      port: 2375

    docker-ionos:
      host: 10.7.0.1
      port: 2375

    docker-ionosxs:
      host: 10.7.0.9
      port: 2375
  proxmox.yaml: |
    pve:
      url: https://192.168.1.27:8006
      token: root@pam!homepage
      secret: c1337400-bccc-43fe-abd9-3e73e862cc4b


