# ingressroute.yaml - Example IngressRoute for a web application
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: pihole
  namespace: pihole
  annotations:
    gethomepage.dev/href: 'https://pihole.homelab.cs-ol.de'
    gethomepage.dev/enabled: 'true'
    gethomepage.dev/description: PiHole
    gethomepage.dev/group: Infrastructure
    gethomepage.dev/icon: si-pihole.png
    gethomepage.dev/app: pihole
    gethomepage.dev/name: PiHole
    gethomepage.dev/widget.type: 'pihole'
    gethomepage.dev/widget.url: 'https://pihole.homelab.cs-ol.de'
    gethomepage.dev/pod-selector: ''
    gethomepage.dev/weight: 10
    #gethomepage.dev/instance: 'public'
spec:
  entryPoints:
    - web
    - websecure
  routes:
    - match: Host(`pihole.homelab.cs-ol.de`)
      kind: Rule
      services:
        - name: pihole-web
          port: 80
#      middlewares:
#        - name: rate-limit
#          namespace: traefik

  tls: {}
#    certResolver: letsencrypt
