# ingressroute.yaml - Example IngressRoute for a web application
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: pihole
  namespace: pihole
spec:
  ingressClassName: traefik-lb
  entryPoints:
    - web
  routes:
    - match: Host(`pihole.homelab.cs-ol.de`)
      kind: Rule
      services:
        - name: pihole-web
          port: 80
      middlewares:
        - name: rate-limit
  tls:
    certResolver: letsencrypt
