apiVersion: kustomize.config.k8s.io/v1beta1

kind: Kustomization

resources:
  - namespace.yaml
  - statefulset.yaml
  - service-dns.yaml
  - service-web.yaml
  - service-headless.yaml
  - nebula-sync.yaml
  - backup.yaml
  - ingress.yaml
  - unifi-sync.yaml

configMapGenerator:
  - name: unifi-sync-scripts
    namespace: pihole
    files:
      - unifi-sync/pihole_sync.py
      - unifi-sync/udm.py
