apiVersion: apps/v1
kind: Deployment
metadata:
  name: pihole
  namespace: pihole
spec:
  template:
    spec:
      containers:
        - name: pihole
          env:
            - name: FTLCONF_LOCAL_IPV4
              value: '10.98.0.200'
