# Created by Ansible (roles/talos create_k8s_secrets) and now managed here with SOPS (#165).
apiVersion: v1
kind: Secret
metadata:
    name: pihole-secret
    namespace: pihole
type: Opaque
data:
    password: ENC[AES256_GCM,data:L/RNrjJgQeoiB3OJ,iv:o4FIPZmMTDxUeciSUtaNk3a4TxZ842TnSb/i/u1KlWM=,tag:As6l8zWHGsRWS6KbG2dwyA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBQNUlYdjNDbDVhbExTVENq
            WThwZVkycmM0aUVEYW4wUjZvQk5lZjBVaGl3CjVFLzBIc2d6N1R5em5sV1A2ZVo5
            c0Q4TGJCQ3k0cWp6K2RyY0I1amlwVTAKLS0tIDlzd2IwRUh6RXlVUll5M1Z5eEwy
            L0JNSGpjT3RHM3lzL2ZHVXE3L0dhVGsKowO7Q7Qt98tEUkO4mobCKThjU/tBnj3d
            m5XnYHIibPcuuVN5tv+1SKtZYy3NZn5o+WbA6ArfwkRrGkywfr1fYw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1zq7k2f07ardejddg6fkxgh8mayu740ytu7hlw36hcr46gdtequ8q4slk2z
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-10-03T15:36:56Z"
    mac: ENC[AES256_GCM,data:wHzBzEVxT95uD1WvZeG1caALeuoPltHACyFVWB0Mcfs96JXFgWysn22MfEOekYZjTYPMJGEDIHdtctN4qAEh2NlGTMpYWB29sWVw8PZPmVgdozqWyLLiyQg19/F6VghMag/44YQwSYyfeeYdsF7hOhKsBysPGnDVcNQYB31aruU=,iv:qqId6imA2guTu4j0waLLsBhvpEsDedU0tF459aY1YYQ=,tag:MfWvROQK2DGErlBoFLo82A==,type:str]
    version: 3.13.3
