apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: pihole
  namespace: pihole
spec:
  replicas: 1
  template:
    spec:
      containers:
        - name: pihole
          env:
            # FTLCONF_LOCAL_IPV4 is a Pi-hole v5 variable and is ignored by v6.
            - name: FTLCONF_dns_reply_host_IPv4
              value: '10.98.0.202'
            - name: FTLCONF_dns_reply_host_force4
              value: 'true'
