---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - metallb/ks-controller.yaml
  - metallb/ks-config.yaml
  - metrics-server/gitrepo.yaml
  - metrics-server/kustomization.yaml
