---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - metallb/ks-controller.yaml
  - metallb/ks-config.yaml
  - cni-plugins/ks.yaml
  - multus/ks.yaml
  - node-feature-discovery/ks.yaml
