apiVersion: v1
kind: Secret
metadata:
    name: smtp-relay-credentials
    namespace: smtp-relay
type: Opaque
stringData:
    RELAYHOST_PASSWORD: ENC[AES256_GCM,data:DgsxLfUNsv5IW3UKSZd/gQ==,iv:bgOjX8O5RdivUgD8hiG6Ky5ePz9PTEGNsWOVWDPNLRo=,tag:YXpUW2CpijKY2ieGQv/wIA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBOUHJSZG1UTVZtOVpnMkFq
            SWdRTWEyQ0JEd2ZGZVIzWXZPeFE1NjJYYVRjCjN5RCs2L20rZVZQMTQ4VWpmSFBY
            UDlCNG9xSmQrckFHK1RMUUtQVVNsQmsKLS0tIGZJRDlZMEVFaGZuTmRCejdLNStN
            MlZKd3NJMjdBNnF3c21KNm80d3c3TmMKPk+5uBkkIrcmFgfqC+yAwNdcw0yXKhw5
            qVd4Vc5/m06WozFrHzTCAw4DxTPb0TH57qc0Q98LfKifL8bsJQfO2w==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1zq7k2f07ardejddg6fkxgh8mayu740ytu7hlw36hcr46gdtequ8q4slk2z
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-25T21:17:39Z"
    mac: ENC[AES256_GCM,data:9ODAEoixHTxY7A4XpM/vppDdQRAccHXJJXI0istyI74cIXH2CamEs9ncddhx4eL1RqComC0gt1tc6JdIh1d/Qyb6u/Wc1adOxMCMf+cgvL4h+NfpYl5For+dxCk2I0/4sYlR+6mJt88ji7Wat+ctbRzjlkBSOe0zYBMQursIDEc=,iv:4QyKw6qF+txgNX0fxhmySfvfJGuLMxzlXqqiIkJI/dY=,tag:H3KceuuDCLPS1h5Jd4wFbg==,type:str]
    version: 3.13.3
