apiVersion: v1
kind: PersistentVolume
metadata:
  name: obsidian-config
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: ""
  mountOptions:
    - nfsvers=3
  nfs:
    server: 192.168.1.240
    path: /homelab/volumes/obsidian/
