apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: multus
  namespace: flux-system

spec:
  interval: 10m
  path: ./infrastructure/multus
  prune: true
  wait: true

  sourceRef:
    kind: GitRepository
    name: flux-system

  dependsOn:
    - name: cni-plugins

  timeout: 5m
