apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: longhorn
  namespace: longhorn-system
  annotations:
    gethomepage.dev/href: 'https://longhorn.homelab.cs-ol.de'
    gethomepage.dev/enabled: 'true'
    gethomepage.dev/description: Longhorn
    gethomepage.dev/group: Infrastructure
    gethomepage.dev/icon: longhorn.png
    gethomepage.dev/app: longhorn
    gethomepage.dev/name: Longhorn
    gethomepage.dev/widget.type: 'longhorn'
    gethomepage.dev/widget.url: 'https://longhorn.homelab.cs-ol.de'
    gethomepage.dev/pod-selector: ''
    gethomepage.dev/weight: 10
    #gethomepage.dev/instance: 'public'
spec:
  entryPoints:
    - websecure
  routes:
    - kind: Rule
      match: Host(`longhorn.homelab.cs-ol.de`)
      services:
        - kind: Service
          name: longhorn-frontend
          port: 80
          sticky:
            cookie:
              httpOnly: true
              secure: true
              sameSite: none
